### ISSUE TITLE
There is no `dapr` in name `dart-sdk` ;)

### ISSUE THREAD

**Issue by pbk0** [Abhilash-Chandran/dart-sdk#3]

**Comment by Abhilash-Chandran** [comment]
Ha ha... Its the convention in the dapr coomunity. Once this goes under dapr organization of which I am sure, it will look like dapr/dart-sdk. ;)

**Comment by pbk0** [comment]
so no dapr-python ... and no cognitive workload of python and dart ... that sounds promising
